# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-pubsub
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: terraform-google-pubsub
  source:
    repo: https://github.com/terraform-google-modules/terraform-google-pubsub
    sourceType: git
  version: 6.0.0
  actuationTool:
    type: Terraform
    version: '>= 0.13'
  examples:
  - name: bigquery
    location: examples/bigquery
  - name: kms
    location: examples/kms
  - name: simple
    location: examples/simple
  - name: subscriptions_only
    location: examples/subscriptions_only
  variables:
  - name: bigquery_subscriptions
    description: The list of the bigquery push subscriptions.
    type: list(map(string))
    default: []
    required: false
  - name: create_subscriptions
    description: Specify true if you want to create subscriptions.
    type: bool
    default: true
    required: false
  - name: create_topic
    description: Specify true if you want to create a topic.
    type: bool
    default: true
    required: false
  - name: grant_token_creator
    description: Specify true if you want to add token creator role to the default Pub/Sub SA.
    type: bool
    default: true
    required: false
  - name: message_storage_policy
    description: A map of storage policies. Default - inherit from organization's Resource Location Restriction policy.
    type: map(any)
    default: {}
    required: false
  - name: project_id
    description: The project ID to manage the Pub/Sub resources.
    type: string
    required: true
  - name: pull_subscriptions
    description: The list of the pull subscriptions.
    type: list(map(string))
    default: []
    required: false
  - name: push_subscriptions
    description: The list of the push subscriptions.
    type: list(map(string))
    default: []
    required: false
  - name: schema
    description: Schema for the topic.
    type: |-
      object({
          name       = string
          type       = string
          definition = string
          encoding   = string
        })
    required: false
  - name: subscription_labels
    description: A map of labels to assign to every Pub/Sub subscription.
    type: map(string)
    default: {}
    required: false
  - name: topic
    description: The Pub/Sub topic name.
    type: string
    required: true
  - name: topic_kms_key_name
    description: The resource name of the Cloud KMS CryptoKey to be used to protect access to messages published on this topic.
    type: string
    required: false
  - name: topic_labels
    description: A map of labels to assign to the Pub/Sub topic.
    type: map(string)
    default: {}
    required: false
  - name: topic_message_retention_duration
    description: The minimum duration in seconds to retain a message after it is published to the topic.
    type: string
    required: false
  outputs:
  - name: id
    description: The ID of the Pub/Sub topic
  - name: subscription_names
    description: The name list of Pub/Sub subscriptions
  - name: subscription_paths
    description: The path list of Pub/Sub subscriptions
  - name: topic
    description: The name of the Pub/Sub topic
  - name: topic_labels
    description: Labels assigned to the Pub/Sub topic
  - name: uri
    description: The URI of the Pub/Sub topic
  roles:
  - level: Project
    roles:
    - roles/pubsub.admin
    - roles/resourcemanager.projectIamAdmin
    - roles/bigquery.admin
  services:
  - cloudresourcemanager.googleapis.com
  - pubsub.googleapis.com
  - serviceusage.googleapis.com
  - bigquery.googleapis.com
