# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-pubsub-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-pubsub
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-pubsub
      sourceType: git
  ui:
    input:
      variables:
        bigquery_subscriptions:
          name: bigquery_subscriptions
          title: Bigquery Subscriptions
          properties:
            name:
              name: name
              title: Name
              regexValidation: ^[a-z][a-z0-9-]{1,253}[a-z0-9]$
              validation: Subscription name must start with a lowercase letter, be between 3 and 255 characters, and contain only lowercase letters, numbers, and hyphens.
            table:
              name: table
              title: Table
              regexValidation: "^[a-z][a-z0-9-]{4,28}[a-z0-9]\\.[a-zA-Z0-9_]{1,1000}[a-zA-Z0-9_]{0,24}\\.[a-zA-Z0-9_]{1,1000}[a-zA-Z0-9_]{0,24}$"
              validation: BigQuery table name must be a full resource path in the format {projectId}.{datasetId}.{tableId}.
            dead_letter_topic:
              name: dead_letter_topic
              title: Dead Letter Topic
              regexValidation: "^projects/([a-z][a-z0-9-]{4,28}[a-z0-9])/topics/([a-z0-9-._~%+]{1,255})$"
              validation: "ID must start with a letter, and contain only the following characters: letters, numbers, dashes (-), periods (.), underscores (_), tildes (~), percents (%) or plus signs (+). Cannot start with goog. ID must be at most 255 characters long."
        cloud_storage_subscriptions:
          name: cloud_storage_subscriptions
          title: Cloud Storage Subscriptions
          properties:
            name:
              name: name
              title: Subscription Name
              regexValidation: ^[a-z][a-z0-9-]{1,253}[a-z0-9]$
              validation: Subscription name must start with a lowercase letter, be between 3 and 255 characters, and contain only lowercase letters, numbers, and hyphens.
            bucket:
              name: bucket
              title: Bucket
              regexValidation: "^[a-z0-9][a-z0-9\\._-]{1,61}[a-z0-9]$"
              validation: Bucket name must start and end with a lowercase letter or number, contain between 3 and 63 characters, and contain only lowercase letters, numbers, dashes, underscores, and dots.
            dead_letter_topic:
              name: dead_letter_topic
              title: Dead Letter Topic
              regexValidation: "^projects/([a-z][a-z0-9-]{4,28}[a-z0-9])/topics/([a-z0-9\\-._~%+]{1,255})$"
              validation: "ID must start with a letter, and contain only the following characters: letters, numbers, dashes (-), periods (.), underscores (_), tildes (~), percents (%) or plus signs (+). Cannot start with goog. ID must be at most 255 characters long."
        create_subscriptions:
          name: create_subscriptions
          title: Create Subscriptions
        create_topic:
          name: create_topic
          title: Create Topic
        grant_bigquery_project_roles:
          name: grant_bigquery_project_roles
          title: Grant Bigquery Project Roles
        grant_cloud_storage_project_roles:
          name: grant_cloud_storage_project_roles
          title: Grant Cloud Storage Project Roles
        grant_token_creator:
          name: grant_token_creator
          title: Grant Token Creator
        message_storage_policy:
          name: message_storage_policy
          title: Message Storage Policy
        project_id:
          name: project_id
          title: Project Id
        pull_subscriptions:
          name: pull_subscriptions
          title: Pull Subscriptions
          properties:
            name:
              name: name
              title: Name
              regexValidation: ^[a-z][a-z0-9-]{1,253}[a-z0-9]$
              validation: Subscription name must start with a lowercase letter, be between 3 and 255 characters, and contain only lowercase letters, numbers, and hyphens.
            dead_letter_topic:
              name: dead_letter_topic
              title: Dead Letter Topic
              regexValidation: "^projects/([a-z][a-z0-9-]{4,28}[a-z0-9])/topics/([a-z0-9\\-._~%+]{1,255})$"
              validation: "ID must start with a letter, and contain only the following characters: letters, numbers, dashes (-), periods (.), underscores (_), tildes (~), percents (%) or plus signs (+). Cannot start with goog. ID must be at most 255 characters long."
            service_account:
              name: service_account
              title: Service Account
              regexValidation: "^[a-z][a-z0-9-]{4,28}[a-z0-9]@[a-z][a-z0-9-]{4,28}[a-z0-9]\\.iam\\.gserviceaccount\\.com$"
              validation: "Service account must be a valid email address in the format: SA_NAME@PROJECT_ID.iam.gserviceaccount.com."
        push_subscriptions:
          name: push_subscriptions
          title: Push Subscriptions
          properties:
            name:
              name: name
              title: Name
              regexValidation: ^[a-z][a-z0-9-]{1,253}[a-z0-9]$
              validation: Subscription name must start with a lowercase letter, be between 3 and 255 characters, and contain only lowercase letters, numbers, and hyphens.
            push_endpoint:
              name: push_endpoint
              title: Push Endpoint
              regexValidation: "^https:\\/\\/[a-zA-Z0-9-.]+\\.[a-zA-Z]{2,}(\\/[^?#]*)?$"
              validation: "Push endpoint must be a valid HTTPS URL."
            dead_letter_topic:
              name: dead_letter_topic
              title: Dead Letter Topic
              regexValidation: "^projects/([a-z][a-z0-9-]{4,28}[a-z0-9])/topics/([a-z0-9\\-._~%+]{1,255})$"
              validation: "ID must start with a letter, and contain only the following characters: letters, numbers, dashes (-), periods (.), underscores (_), tildes (~), percents (%) or plus signs (+). Cannot start with goog. ID must be at most 255 characters long."
            oidc_service_account_email:
              name: oidc_service_account_email
              title: OIDC Service Account Email
              regexValidation: "^[a-z][a-z0-9-]{4,28}[a-z0-9]@[a-z][a-z0-9-]{4,28}[a-z0-9]\\.iam\\.gserviceaccount\\.com$"
              validation: "OIDC service account email must be a valid email address in the format: SA_NAME@PROJECT_ID.iam.gserviceaccount.com."
        schema:
          name: schema
          title: Schema
          properties:
            name:
              name: name
              title: Name
              regexValidation: ^[a-z][a-z0-9-]{1,253}[a-z0-9]$
              validation: Schema name must start with a lowercase letter, be between 3 and 255 characters, and contain only lowercase letters, numbers, and hyphens.
            type:
              name: type
              title: Type
              enumValueLabels:
                - label: TYPE_UNSPECIFIED
                  value: TYPE_UNSPECIFIED
                - label: PROTOCOL_BUFFER
                  value: PROTOCOL_BUFFER
                - label: AVRO
                  value: AVRO
            encoding:
              name: encoding
              title: Encoding
              enumValueLabels:
                - label: BINARY
                  value: BINARY
                - label: JSON
                  value: JSON
                - label: ENCODING_UNSPECIFIED
                  value: ENCODING_UNSPECIFIED
        subscription_labels:
          name: subscription_labels
          title: Subscription Labels
        topic:
          name: topic
          title: Topic
          regexValidation: ^([a-fh-zA-FH-Z][a-zA-Z0-9\-._~%+]{0,254}|[gG]($|[^oO][a-zA-Z0-9\-._~%+]{0,253}|[oO]($|[^oO][a-zA-Z0-9\-._~%+]{0,252}|[oO]($|[^gG][a-zA-Z0-9\-._~%+]{0,251}))))$
          validation: "ID must start with a letter, and contain only the following characters: letters, numbers, dashes (-), periods (.), underscores (_), tildes (~), percents (%) or plus signs (+). Cannot start with goog. ID must be at most 255 characters long."
        topic_kms_key_name:
          name: topic_kms_key_name
          title: Topic Kms Key Name
        topic_labels:
          name: topic_labels
          title: Topic Labels
        topic_message_retention_duration:
          name: topic_message_retention_duration
          title: Topic Message Retention Duration
    runtime:
      outputs:
        service_uri:
          visibility: VISIBILITY_ROOT
